### ISSUE TITLE
I cannot make the 'process.py' script work

### ISSUE THREAD

**Issue by ThomasA** [ReScience/articles#19]
I am trying to publish https://github.com/ReScience/submissions/issues/27#. I am following the instructions in https://github.com/ReScience/articles/blob/master/README.md. I can run 'process.py' just fine with the `--sandbox` option, but it fails when I try the `--zenodo` option:

    $ ./process.py --zenodo --metadata metadata.yaml --pdf article.pdf
    Traceback (most recent call last):
      File "./process.py", line 77, in <module>
        article_id, article_doi = reserve_doi(server, token)
      File "./process.py", line 21, in reserve_doi
        response.json()["message"])
    OSError: 401: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

Both my `ZENODO_SANDBOX_TOKEN` and `ZENODO_TOKEN` are set. I have both tried setting `ZENODO_TOKEN` to the same as `ZENODO_SANDBOX_TOKEN` as well as setting it to a separately created token. Neither works and both give me the same error message.

**Comment by ThomasA** [comment]
My bad: I had created both tokens on the Sandbox server :man_facepalming:
